FROM alpine:3.14
CMD ["echo", "Olá mundo!"]

# pessoa@trybe:~$ docker run --rm exemplo-entrypoint
# Olá mundo!
# pessoa@trybe:~$

# pessoa@trybe:~$ docker run --rm exemplo-entrypoint "Sou diferente!"
# Olá mundo! Sou diferente!
# pessoa@trybe:~$