FROM alpine:3.14
ENTRYPOINT ["echo"]
CMD ["Sou a mensagem padrão."]

# pessoa@trybe:~$ docker run --rm exemplo-entrypoint-cmd
# Sou a mensagem padrão.
# pessoa@trybe:~$

# pessoa@trybe:~$ docker run --rm exemplo-entrypoint-cmd "Sou uma mensagem nova!"
# Sou uma mensagem nova!
# pessoa@trybe:~$